id: P008023
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:56:11.039878
source_metadata:
  id: bdr:W28996
  title: གསུང་ཐོར་བུ། བློ་གྲོས་རྒྱ་མཚོ
  author: ''
  volumes:
    986b7111e7354e5f906c640eef21ca0e:
      image_group_id: I4975
      title: ''
      volume_number: 1
      total_pages: 296
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
