id: I2DBDF5C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:43:14+00:00'
last_modified: '2022-06-08T17:53:13.405243+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28996
  title: གསུང་ཐོར་བུ། བློ་གྲོས་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1CA3:
      image_group_id: I4975
      title: ''
      total_pages: 296
      order: 1
      base_file: 1CA3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
